version: '3'

services:
  database:
    image: postgres:${POSTGRES_VERSION:-14}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-budget}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    networks:
      - budget_network
    ports:
      - 5432:5432
    volumes:
      - db_data:/srv/lib/postgresql/data:rw

  php:
    build: ./docker/php
    depends_on:
      - database
    networks:
      - budget_network
    volumes:
      - ./:/srv/www

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    depends_on:
      - php
    networks:
      - budget_network
    ports:
      - 8080:80
      - 443:443
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./docker/caddy/config:/config
      - ./docker/caddy/access.log:/var/log/caddy/access.log
      - ./:/srv/www
      - caddy_data:/data

volumes:
  db_data:
  caddy_data:


networks:
  budget_network:
