version: '3'

services:
  database:
    image: postgres:${POSTGRES_VERSION:-14}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-budget}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    networks:
      - budget_network
    ports:
      - 5432:5432
    volumes:
      - db_data:/srv/lib/postgresql/data:rw

  php:
    build: ./docker/php
    networks:
      - budget_network
    ports:
      - 9000:9000
    volumes:
      - ./:/var/www/symfony_docker
    depends_on:
      - database

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    networks:
      - budget_network
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/symfony_docker
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

volumes:
  db_data:
  caddy_data:


networks:
  budget_network:
